### PR TITLE
Collective bargaining

### LINKED ISSUE #49: Parser frequently breaks with parenthesized expressions
### Version

`cadf474`

### Environment

All environments

### Description

Any expression that begins with an identifier parses incorrectly when parenthesized, because the parser treats it as a typed parameter.

### Steps To Reproduce

```haskell
fool.silt:1:20: error: unexpected token ')' (expected ':')
foo a b c = (a b c)
                  ^ 
```

### Expected Result

That should just parse as a ParenExpr with an ApplicationExpr inside.

### Actual Result

The error above.

### Additional Information

We should do better at detecting typed parameters.

### PR DESCRIPTION
**Pull request by CodaFi**
- Collapse SyntaxCollection subclasses into typealiases:

SyntaxGen now synthesizes a dictionary of `ObjectIdentifier`s mapping collection element archetypes to syntax kinds.  This now means that

1) It is no longer possible to declare two SyntaxCollections containing the same element type with different element types.  (I think this restriction can be lifted with some creativity).
2) SyntaxCollection's mutating functions can be used without consequence.

- Break ambiguity in parsing parenthesized expressions

Fixes #49 by removing the special case for arrow-containing parameter lists.  Instead, parse the parameter part as a basic expression and the arrow part and output part as an application expression like everything else.

### CODE REVIEW

File: Sources/Crust/Parser.swift [hunk 1]
```diff
@@ -564,18 +564,79 @@ extension Parser {
...
-    if isStartOfTypedParameter() {
-      return try self.parseTypedParameterArrowExpr()
+  // Breaks the ambiguity in parsing the beginning of a typed parameter
+  //
+  // (a b c ... : <expr>)
+  //
+  // and the beginning of an application expression
+  //
+  // (a b c ...)
+  func parseParenthesizedExpr() throws -> BasicExprSyntax {
```
Comment (harlanhaskins) [inline Sources/Crust/Parser.swift:583]: This is waaaaaaay better, thank you!

**Comment by harlanhaskins** [comment]
Can we get a test for the new grammatical productions?

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
🚢 :it:
